### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by cdeil** [gablaxian/super-js-adventure#2]
At https://github.com/gablaxian/super-js-adventure at the top there's a link to  http://gablaxian.com/articles/creating-a-game-with-javascript/

Where can I find the description? Where can I try out the game?

**Comment by gablaxian** [comment]
Ah, apologies. I removed the 'landing page' a while ago and never set up any redirects!

Please head here: [https://gablaxian.com/articles/creating-a-game-with-javascript/introduction](https://gablaxian.com/articles/creating-a-game-with-javascript/introduction)

**Comment by cdeil** [comment]
Thank you!
